import { Script, User } from "@/types";

export const mockUser: User = {
  id: "u1",
  username: "jane-doe",
  displayName: "Jane Doe",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane",
  bio: "Screenwriter & director. I live at the intersection of science fiction and intimate human drama.",
  focus: "Drama · Sci-Fi · Thriller",
  github: "https://github.com",
  twitter: "https://twitter.com",
  imdb: "https://imdb.com",
  stats: { scripts: 12, forks: 87, reads: 4302 },
  scripts: [],
};

export const mockScripts: Script[] = [
  {
    id: "s1",
    title: "Echoes of Andromeda",
    logline: "A deep-space botanist discovers a signal that could rewrite human history — if she can survive long enough to broadcast it.",
    genre: ["Sci-Fi", "Thriller"],
    coverImage: "/covers/andromeda.jpg",
    author: { id: "u1", username: "jane-doe", displayName: "Jane Doe", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane", bio: "", focus: "Sci-Fi", github: undefined, twitter: undefined, imdb: undefined },
    forks: 42,
    reads: 1820,
    tags: ["space", "mystery", "survival"],
    createdAt: "2025-11-01",
    updatedAt: "2026-01-15",
    blocks: [
      { id: "b1", type: "scene-heading", content: "EXT. ANDROMEDA STATION — AIRLOCK — DAY" },
      { id: "b2", type: "action", content: "A lone figure in a battered EVA suit clings to the hull. Stars drift silently behind her." },
      { id: "b3", type: "character", content: "DR. MARA QUINN" },
      { id: "b4", type: "dialogue", content: "Houston, I've found something. I don't think they're going to believe me." },
    ],
  },
  {
    id: "s2",
    title: "The Cartographer's Daughter",
    logline: "When her father vanishes in the Amazon, a young cartographer follows his final map into a civilization that defies all record.",
    genre: ["Adventure", "Drama"],
    coverImage: "/covers/cartographer.jpg",
    author: { id: "u2", username: "alex-river", displayName: "Alex River", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex", bio: "", focus: "Drama", github: undefined, twitter: undefined, imdb: undefined },
    forks: 28,
    reads: 930,
    tags: ["adventure", "mystery", "jungle"],
    createdAt: "2025-09-12",
    updatedAt: "2025-12-03",
    blocks: [],
  },
  {
    id: "s3",
    title: "Last Light at Dusk",
    logline: "An aging jazz musician reconnects with estranged family over a single legendary evening in New Orleans.",
    genre: ["Drama"],
    coverImage: "/covers/dusk.jpg",
    author: { id: "u3", username: "maya-chen", displayName: "Maya Chen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya", bio: "", focus: "Drama", github: undefined, twitter: undefined, imdb: undefined },
    forks: 15,
    reads: 502,
    tags: ["family", "music", "nostalgia"],
    createdAt: "2026-01-20",
    updatedAt: "2026-02-28",
    blocks: [],
  },
  {
    id: "s4",
    title: "Ghost Protocol: Venice",
    logline: "A retired intelligence officer is pulled back in when her former handler surfaces — as the prime suspect in a string of impossible heists.",
    genre: ["Thriller", "Action"],
    coverImage: "/covers/venice.jpg",
    author: { id: "u4", username: "marco-v", displayName: "Marco Valentini", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marco", bio: "", focus: "Thriller", github: undefined, twitter: undefined, imdb: undefined },
    forks: 63,
    reads: 2100,
    tags: ["spy", "heist", "europe"],
    createdAt: "2025-07-04",
    updatedAt: "2026-03-01",
    blocks: [],
  },
  {
    id: "s5",
    title: "Silicon Pastoral",
    logline: "In 2047, a rural community fights to preserve its land against an AI agricultural conglomerate — and discovers the land is already fighting back.",
    genre: ["Sci-Fi", "Drama"],
    coverImage: "/covers/pastoral.jpg",
    author: { id: "u1", username: "jane-doe", displayName: "Jane Doe", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane", bio: "", focus: "Sci-Fi", github: undefined, twitter: undefined, imdb: undefined },
    forks: 31,
    reads: 789,
    tags: ["ai", "nature", "community"],
    createdAt: "2026-02-14",
    updatedAt: "2026-03-20",
    blocks: [],
  },
  {
    id: "s6",
    title: "Midnight Theorem",
    logline: "A mathematics prodigy at Oxford cracks a centuries-old cipher — and realizes it was meant to be cracked right now.",
    genre: ["Thriller", "Mystery"],
    coverImage: "/covers/theorem.jpg",
    author: { id: "u5", username: "priya-s", displayName: "Priya Sharma", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya", bio: "", focus: "Thriller", github: undefined, twitter: undefined, imdb: undefined },
    forks: 55,
    reads: 1450,
    tags: ["math", "conspiracy", "oxford"],
    createdAt: "2025-10-30",
    updatedAt: "2026-01-09",
    blocks: [],
  },
];

// The script used in the demo editor
export const demoScript: Script = mockScripts[0];

// The logged-in user's scripts
mockUser.scripts = [mockScripts[0], mockScripts[4]];
